---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: diploma
spec:
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/path: "/health"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-046-13/momo-store/backend:08a3b955a96d61acc670745898eac698499971f7
          name: backend
          imagePullPolicy: IfNotPresent
          ports:
            - name: backend
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          resources:
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 0.5
              memory: 512Mi
      imagePullSecrets:
        - name: docker-secret
