apiVersion: v2
name: backend-momo-store-chart
description: A backend Helm chart for momo store
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
