---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: docker-config
type: kubernetes.io/dockerconfigjson
