namespace: diploma

image:
  repository: grafana/loki
  tag: "3.0.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

service:
  port: 3100
